source project_config.sh
STEP="parse_strelka"

#3 parse_strelka:
#    --strelka_snv_raw s: SNV output file generated by Stelka run.  Required
#    --strelka_config s: path to strelka.ini file.  Required
#    --strelka_vcf_filter_config: Configuration file for strelka VCF filtering (depth, VAF, read count).  Required
#    --dbsnp_db s: database for dbSNP filtering.  Required
#    --results_dir s: Per-sample analysis results location. Often same as sample name [.]

# "/usr/local/somaticwrapper/vcf_filters/vcf_filter_config.ini"

# This is dependent on whether Strelka1 or Strelka2 is used
STRELKA_SNV_RAW="results/strelka/strelka_out/results/variants/somatic.snvs.vcf.gz"

ARGS="\
--strelka_snv_raw $STRELKA_SNV_RAW \
--strelka_config $STRELKA_CONFIG \
--strelka_vcf_filter_config $STRELKA_VCF_FILTER_CONFIG \
--dbsnp_db $DBSNP_DB \
--results_dir $RESULTS_DIR \
"

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

# Output: results/strelka/filter_out/strelka.somatic.snv.all.dbsnp_pass.filtered.vcf

