DATAD="/usr/local/somaticwrapper/testing/StrelkaDemo.dat"
source project_config.sh $DATAD

STEP="parse_varscan_indel"

# parse_varscan_indel:
#     --varscan_indel_raw s: Indel output file generated by varscan run.  Required
#     --varscan_config s: path to varscan.ini file.  Required

VARSCAN_INDEL_RAW="results/varscan/varscan_out/varscan.out.som_indel.vcf"

ARGS="\
--varscan_indel_raw $VARSCAN_INDEL_RAW \
--varscan_config $VARSCAN_CONFIG \
--results_dir $RESULTS_DIR \
"

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

