DATAD="/usr/local/somaticwrapper/testing/StrelkaDemo.dat"
source project_config.sh $DATAD

STEP="parse_pindel"

#parse_pindel:
#    --pindel_config s: path to pindel.ini file.  Required
#    --pindel_raw s: raw output file generated by pindel run.  Required 
#    --reference_fasta s: path to reference.  Required
#    --no_delete_temp : if defined, do not delete temp files
#    --bypass_cvs : skip filtering for CvgVafStrand in pindel_filter
#    --bypass_homopolymer : skip filtering for Homopolymer in pindel_filter
#    --bypass : bypass all filters
#    --debug: print out processing details to STDERR

PINDEL_RAW="results/pindel/pindel_out/pindel-raw.dat"

ARGS="\
--pindel_config $PINDEL_CONFIG \
--pindel_raw $PINDEL_RAW \
--reference_fasta $REFERENCE_FASTA \
--results_dir $RESULTS_DIR \
--no_delete_temp \
--bypass \
"
#--no_delete_temp \
#--bypass \

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

