source project_config.sh

STEP="parse_varscan"

#4 parse_varscan:
#    --varscan_snv_raw s: Path to SNV output file generated by varscan run.  Required.
#    --varscan_indel_raw s: Indel output file generated by varscan run.  Required
#    --varscan_config s: path to varscan.ini file.  Required
#    --dbsnp_db s: database for dbSNP filtering.  Required
#    --varscan_vcf_filter_config: Configuration file for varscan VCF filtering.  Required
#    --results_dir s: Per-sample analysis results location. Often same as sample name [.] 

VARSCAN_SNV_RAW="results/varscan/varscan_out/varscan.out.som_snv.vcf"
VARSCAN_INDEL_RAW="results/varscan/varscan_out/varscan.out.som_indel.vcf"

ARGS="\
--varscan_snv_raw $VARSCAN_SNV_RAW \
--varscan_indel_raw $VARSCAN_INDEL_RAW \
--varscan_config $VARSCAN_CONFIG \
--dbsnp_db $DBSNP_DB \
--varscan_vcf_filter_config $VARSCAN_VCF_FILTER_CONFIG \
--results_dir $RESULTS_DIR \
"

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

# Output:
# * results/varscan/filter_out/varscan.out.som_snv.Somatic.hc.somfilter_pass.dbsnp_pass.filtered.vcf
# * results/varscan/filter_out/varscan.out.som_indel.Somatic.hc.dbsnp_pass.filtered.vcf

