source project_config.sh

STEP="merge_vcf"
#8 merge_vcf:
#    --strelka_snv_vcf s: output file generated by parse_strelka.  Required
#    --varscan_snv_vcf s: output file generated by parse_varscan.  Required
#    --varscan_indel_vcf s: output file generated by parse_varscan.  Required
#    --pindel_vcf s: output file generated by parse_pindel.  Required
#    --reference_fasta s: path to reference.  Required
#    --results_dir s: Per-sample analysis results location. Often same as sample name [.] 
#    --bypass: Bypass filter by retaining all reads


# results/strelka/filter_out/strelka.somatic.snv.all.dbsnp_pass.filtered.vcf
# results/varscan/filter_out/varscan.out.som_snv.Somatic.hc.somfilter_pass.dbsnp_pass.filtered.vcf
# results/varscan/filter_out/varscan.out.som_indel.Somatic.hc.dbsnp_pass.filtered.vcf
# results/pindel/filter_out/pindel.out.current_final.dbsnp_pass.filtered.vcf

STRELKA_SNV_VCF="results/strelka/filter_out/strelka.somatic.snv.all.dbsnp_pass.filtered.vcf"
VARSCAN_SNV_VCF="results/varscan/filter_out/varscan.out.som_snv.Somatic.hc.somfilter_pass.dbsnp_pass.filtered.vcf"
VARSCAN_INDEL_VCF="results/varscan/filter_out/varscan.out.som_indel.Somatic.hc.dbsnp_pass.filtered.vcf"
PINDEL_VCF="results/pindel/filter_out/pindel.out.current_final.dbsnp_pass.filtered.vcf"

ARGS="\
--strelka_snv_vcf $STRELKA_SNV_VCF \
--varscan_snv_vcf $VARSCAN_SNV_VCF \
--varscan_indel_vcf $VARSCAN_INDEL_VCF \
--pindel_vcf $PINDEL_VCF \
--reference_fasta $REFERENCE_FASTA \
--results_dir $RESULTS_DIR \
"
#--bypass \

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

# Result: results/merged/merged.filtered.vcf
