DATAD="/usr/local/somaticwrapper/testing/StrelkaDemo.dat"
source project_config.sh $DATAD

STEP="parse_pindel"
#7 parse_pindel:
#    --pindel_vcf_filter_config: Configuration file for pindel VCF filtering 
#    --pindel_config s: path to pindel.ini file.  Required
#    --pindel_raw s: raw output file generated by pindel run.  Required 
#    --reference_fasta s: path to reference.  Required
#    --dbsnp_db s: database for dbSNP filtering.  Required
#    --results_dir s: Per-sample analysis results location. Often same as sample name [.] 
#    --no_delete_temp : if defined, do not delete temp files

PINDEL_RAW="results/pindel/pindel_out/pindel-raw.dat"

ARGS="\
--pindel_vcf_filter_config $PINDEL_VCF_FILTER_CONFIG \
--pindel_config $PINDEL_CONFIG \
--pindel_raw $PINDEL_RAW \
--reference_fasta $REFERENCE_FASTA \
--dbsnp_db $DBSNP_DB \
--results_dir $RESULTS_DIR \
"
#--no_delete_temp \
#--bypass \

BIN="/usr/local/somaticwrapper/SomaticWrapper.pl"
perl $BIN $ARGS $STEP

